spring:
  application.name: spring-multiple-datasource
  account-datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:accounts;DATABASE_TO_UPPER=true;DB_CLOSE_DELAY=-1
    username: sa
    password:
  procedure-datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    jdbc-url: jdbc:hsqldb:mem:procedures;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2.console.enabled: true

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
